branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: ScoreSheet
  default_ec2_keyname: null
  default_platform: Ruby 2.2 (Puma)
  default_region: us-west-2
  profile: eb-cli
  sc: git
